spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/msoficinasdb
    username: postgres
    password: 102030
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
